"""Add timezone to datetime columns

Revision ID: 7fbaa6389247
Revises: 5ef2838e506e
Create Date: 2024-05-05 18:59:50.253815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbaa6389247'
down_revision: Union[str, None] = '5ef2838e506e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Create a new table with the updated schema
    #op.drop_table('bot_last_message')
    op.create_table('new_waat_words',
                    sa.Column('id', sa.Integer, primary_key=True, nullable=False, autoincrement=True),
                    sa.Column('word', sa.String),
                    sa.Column('timestamp', sa.DateTime(timezone=True)),
                    sa.Column('user', sa.String),
                    sa.Column('createdOn', sa.DateTime(timezone=True)),
                    sa.Column('meta_message', sa.String),
                    sa.Column('avatar_url', sa.String),
                    )
    # Copy data from old to new table
    op.execute('INSERT INTO new_waat_words (id, word, timestamp, user, createdOn, meta_message, avatar_url) SELECT id, word, timestamp, user, createdOn, meta_message, avatar_url FROM waat_words')
    # Drop the old table
    op.drop_table('waat_words')
    # Rename the new table
    op.rename_table('new_waat_words', 'waat_words')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waat_words', 'meta_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('waat_words', 'user',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('waat_words', 'word',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('waat_words', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('bot_last_message',
    sa.Column('channel_id', sa.INTEGER(), nullable=True),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id')
    )
    # ### end Alembic commands ###
