name: Docker Image CD

on:
  push:
    branches: [ "Dev" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker Image
      run: |
        docker build -t adrianedelen/ballboinewdev:latest .
        docker push adrianedelen/ballboinewdev:latest
